title: TICP1024 - VDM
description: Analizar la aplicación de principios de diseño y técnicas de interacción para la visualización de información mediante el uso de representaciones gráficas eficaces y efectivas.
theme: just-the-docs

url: https://aavendan.github.io/TICP1024

toc:
  title: "Tabla de contenidos"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-pdf-embed
  - jekyll-toc