title: TICP1024
description: Analizar la aplicación de principios de diseño y técnicas de interacción para la visualización de información mediante el uso de representaciones gráficas eficaces y efectivas.
theme: just-the-docs

url: https://aavendan.github.io/TICP1024
