title: TICP1024 - VDM
description: Analizar la aplicación de principios de diseño y técnicas de interacción para la visualización de información mediante el uso de representaciones gráficas eficaces y efectivas.
theme: just-the-docs

url: https://aavendan.github.io/TICP1024

toc:
  title: "Tabla de contenidos"

callouts:
  highlight:
    title: Para recordar
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    title: Información
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Advertencia
    color: red
  definition:
    title: Definición
    color: cyan

plugins:
  - jekyll-pdf-embed
  - jekyll-toc